<h1>Setup</h1>
<form class="form-horizontal" id="initForm">
<input type="hidden" name="randgen" value="<?php echo $RESOURCE['randgen']; ?>" />
<?php
// $Id: orders_phase0.php 203 2014-03-23 07:55:38Z paul $

// Get selection options
require_once("utl_territory_form.php");
// All info should be in the SR_ORDERXML order, generated by SR_MOVE_QUEUE_INCM
$result = $mysqli -> query ("select order_code From sp_orders Where gameno=$gameno and userno=$userno and ordername='SR_ORDERXML'");
$row = $result -> fetch_row();
$result -> close();

libxml_use_internal_errors(true);
$orderxml = SimpleXML_Load_String($row[0]);
$Minerals = $orderxml -> Minerals;
$Oil = $orderxml -> Oil;
$Grain = $orderxml -> Grain;
$Major = $orderxml -> Major;

?>
<div style="align:center">
    <div class="control-group">
        <label class="control-label">Minerals</label>
        <div class="controls"><input type="number" class="input-mini initVal" id="Minerals" name="Minerals" data-start="<?php echo $Minerals; ?>" value="<?php echo $Minerals; ?>" min="0" max="9" /></div>
    </div>

    <div class="control-group">
        <label class="control-label">Oil</label>
        <div class="controls"><input type="number" class="input-mini initVal" id="Oil" name="Oil" data-start="<?php echo $Oil; ?>" value="<?php echo $Oil; ?>"  min="0" max="9" /></div>
    </div>

    <div class="control-group">
        <label class="control-label" for="Grain">Grain</label>
        <div class="controls"><input type="number" class="input-mini initVal" id="Grain" name="Grain" data-start="<?php echo $Grain; ?>" value="<?php echo $Grain; ?>" min="0" max="9" readonly /></div>
    </div>

    <div class="control-group">
        <label class="control-label">Place Tank</label>
        <div class="controls"><select class="input-medium initVal" id="major" name="Major" data-start="<?php echo $Major; ?>"><?php buildTerrOptions($gameno, $userno, 'LAND', $Major); ?></select></div>
    </div>

<?php for ($i=1; $i<=9; $i++) { ?>
    <div class="control-group">
      <?php if ($i==1) { ?><label class="control-label">Place Armies or Navies</label><?php } ?>
        <div class="controls">
          <?php $name = "Minor$i"; $selected = $orderxml -> $name; ?>
          <select class="input-medium initVal" id="<?php echo $name?>" name="<?php echo $name?>" data-start="<?php echo $selected; ?>">
            <?php buildTerrOptions($gameno, $userno, 'ANY', $selected); ?>
          </select>
        </div>
    </div>
<?php } ?>

  <div class="control-group">
    <div class="controls">
      <input type="button" value="Process Orders" id="initOK" name="PROCESS" class="btn btn-primary" />
    </div>
  </div>
</div>
</form>
