<h1>Pay Salaries</h1>
<form class="form-horizontal" method="post">
<?php

// $Id: orders_phase1.php 237 2014-07-10 07:28:53Z paul $

// All info should be in the SR_ORDERXML order, generated by SR_MOVE_QUEUE_INCM
$result = $mysqli -> query ("select order_code From sp_orders Where gameno=$gameno and userno=$userno and ordername='SR_ORDERXML'");
$row = $result -> fetch_row();
$result -> close();

libxml_use_internal_errors(true);
$orderxml = SimpleXML_Load_String($row[0]);

// Get information from the XML
$income = $orderxml -> Income -> Credit;
$cash = $orderxml -> Balance -> Credit;
$cost = $orderxml -> PayBank -> Cost;
$outstanding = $orderxml -> PayBank -> Outstanding;
$repay = $orderxml -> PayBank -> Repay;
$bond_value = $orderxml -> Income -> BondValue;
$tbond = $orderxml -> PayBank -> Bond;
$loan = $RESOURCE['loan'];
$randgen = $RESOURCE['randgen'];

// Check current cash amount
$result = $mysqli -> query ("select cash from sp_resource where gameno=$gameno and powername='$powername'");
$row = $result -> fetch_row();
$result -> close();
$cash = $row[0];

?>
<input type="hidden" name="randgen" value="<?php echo $randgen; ?>" />
<div class="row-fluid" style="padding-top:20px">
  <div class="span9"><h3><i id='statement' class="icon-plus-sign"></i> Bank Statement</h3></div>
  <div class="span3 control-group" align="right">
    <input id="bankTotal" class="input-mini" type="text" align="right" readonly value="0" />
  </div>
</div><!-- row -->
<div id='statementDetail' style='display:none'>
  <div class="row-fluid">
    <div class="span6">Initial cash</div>
    <div class="span5 control-group" align="right">
      <input id="cashValue" name="cashValue" class="input-mini incoming" type="text" align="right" readonly value="<?php echo $cash; ?>" />
    </div>
  </div><!-- row -->
  <div class="row-fluid">
    <div class="span8">Territory Income</div>
    <div class="span3 control-group" align="right">
      <input id="territoryValue" class="input-mini incoming" type="text" align="right" readonly value="<?php echo $income; ?>" />
    </div>
  </div><!-- row -->
  <?php if ($GAME['turnno'] > 3 and $RESOURCE['boomer_money']=='N') { ?>
      <div class="row-fluid">
        <div class="span3">Bond value</div>
        <div class="span5"><label class="checkbox"><input id="tbond" name="tbond" value="0" type="hidden" /><input id="takeBond" type="checkbox" <?php echo $tbond=="Y"?"checked":""; ?> /> Take bond</label></div>
        <div class="span3 control-group" align="right">
          <input id="bondTaken" class="input-mini incoming" type="text" align="right" readonly value="0" />
          <input id="bondValue" type="hidden" readonly value="<?php echo $bond_value; ?>" />
        </div>
      </div><!-- row -->
  <?php } else { ?>
    <input id="tbond" type="hidden" name="tbond" readonly value="0" />
    <input id="takeBond" type="hidden" readonly value="" />
    <input id="bondTaken" type="hidden" readonly value="0" />
    <input id="bondValue" type="hidden" readonly value="<?php echo $bond_value; ?>" />
  <?php } ?>
  <div class="row-fluid">
    <div class="span3">Interest</div>
    <div class="span2"><input id="interestOutstanding" class="input-mini" type="text" align="right" readonly value="<?php echo $outstanding; ?>" /></div>
    <div class="span6 control-group" align="right" id="interestCont">
      <label class="control-label" for="interestValue">Pay</label>
      <div class="controls">
        <div class="input-prepend">
          <span class="add-on">-</span>
          <select class="input-small outgoing" name="Interest" id="interestValue">
            <?php for ($i=0; $i*50 <= $outstanding; $i++) { echo '<option '.($i*50==$cost?'selected':'').'>'. $i*50 .'</option>'; } ?>
          </select>
        </div>
      </div>
      <div class="alert" id="interestWarning" style="display:none">You will be unable to trade with the Market if interest is outstanding</div>
    </div><!-- control group -->
  </div><!-- row -->
  <div class="row-fluid">
    <div class="span3">Loan</div>
    <div class="span2"><input class="input-mini" type="text" align="right" readonly value="<?php echo $loan; ?>" /></div>
    <div class="span6 control-group" align="right">
      <label class="control-label" for="repayLoan">Repay</label>
      <div class="controls">
        <div class="input-prepend">
          <span class="add-on">-</span>
          <select id="loanValue" class="input-small outgoing" name="Repay">
            <?php for ($i=0; $i*1000 <= $loan; $i++) { echo '<option '.($i*1000==$repay?'selected':'').'>'. $i*1000 .'</option>';} ?>
          </select>
        </div>
      </div>
    </div><!-- control group -->
  </div><!-- row -->
</div><!-- statement detail -->



<div class="row-fluid" style="padding-top:20px">
  <div class="span9"><h3><i id='troops' class="icon-plus-sign"></i> Pay Troops</h3></div>
  <div class="span3 control-group" align="right"><div class="input-prepend"><span class="add-on">-</span><input id="troopTotal" name="troopTotal" class="input-mini subTotal" type="text" align="right" readonly value="0" /></div></div>
</div><!-- row -->
<div class="row-fluid" id="troopWarn" style="display:none"><div class="span12" align="right"><span class="label label-warning">Not all troops are being paid</span></div></div>
<div id='troopsDetail' style='display:none'>

<?php
// Land territory payments
$query = "Select p.terrname, b.terrno, b.minor, b.major
          From sp_places p, sp_board b
          Where b.gameno=$gameno
           and b.userno=$userno
           and p.terrno=b.terrno
           and Length(p.terrtype)=4
          Order By p.terrname
          ;";
?><div class="row-fluid"><div class="span3"></div><div class="span3">Tanks</div><div class="span3">Armies</div><div class="span3"></div></div><?php
$result = $mysqli -> query($query) or die ($mysqli -> error);
while ($row = $result -> fetch_row()) {?>
  <div class="row-fluid terrRow">
    <div class="span3"><?php echo $row[0]; ?></div>
    <div class="span3 control-group">
      <select id="T<?php echo $row[1]; ?>" name="T<?php echo $row[1]; ?>" class="input-mini troops">
        <?php
          $order = $orderxml -> xpath("/PAYSALARIES/PayTroops[text()='".$row[0]."']/Major");
          for ($i=0; $i <= $row[3]; $i++) {
            if ($order[0][0]==$i) printf("<option selected>%s</option>",$i);
            else printf("<option>%s</option>",$i);
          } ?>
      </select>
    </div>
    <div class="span3 control-group">
      <select id="M<?php echo $row[1]; ?>" name="M<?php echo $row[1]; ?>" class="input-mini troops">
        <?php
          $order = $orderxml -> xpath("/PAYSALARIES/PayTroops[text()='".$row[0]."']/Minor");
          for ($i=0; $i <= $row[2]; $i++) {
            if ($order[0][0]==$i) printf("<option selected>%s</option>",$i);
            else printf("<option>%s</option>",$i);
          } ?>
      </select>
    </div>
    <div class="span2 control-group" align="right">
      <input id="t1Value" name="t1Value" class="input-mini troopSum" type="text" align="right" readonly value="0" />
    </div>
  </div><!-- territory row --><?php
}
$result -> close();

// Sea territory payments
$query = "Select p.terrname, b.terrno, b.minor, b.major
          From sp_places p, sp_board b
          Where b.gameno=$gameno
           and b.userno=$userno
           and p.terrno=b.terrno
           and Length(p.terrtype)=3
          Order By p.terrname
          ;";
?><div class="row-fluid"><div class="span3"></div><div class="span3">Boomers</div><div class="span3">Navies</div><div class="span3"></div></div><?php
$result = $mysqli -> query($query) or die ($mysqli -> error);
while ($row = $result -> fetch_row()) {?>
  <div class="row-fluid terrRow">
    <div class="span3"><?php echo $row[0]; ?></div>
    <div class="span3 control-group">
        <?php $order = $orderxml -> xpath("/PAYSALARIES/PayTroops[text()='".$row[0]."']/Boomers[text()]"); echo $order[0][0]; ?>
    </div>
    <div class="span3 control-group">
      <select id="M<?php echo $row[1]; ?>" name="M<?php echo $row[1]; ?>" class="input-mini troops">
        <?php
          $order = $orderxml -> xpath("/PAYSALARIES/PayTroops[text()='".$row[0]."']/Minor");
          for ($i=0; $i <= $row[2]; $i++) {
            if ($order[0][0]==$i) printf("<option selected>%s</option>",$i);
            else printf("<option>%s</option>",$i);
          } ?>
      </select>
    </div>
    <div class="span2 control-group" align="right">
      <input id="t2Value" name="t2Value" class="input-mini troopSum" type="text" align="right" readonly value="0" />
    </div>
  </div><!-- territory row --><?php
} ?>
</div><!-- troops detail -->



<div class="row-fluid" style="padding-top:20px">
  <div class="span9"><h3><i id='companies' class="icon-plus-sign"></i> Pay Companies</h3><input type="hidden" id="resourceReopen" value="<?php echo 50+$GAME['company_restart_cost']; ?>" /><input type="hidden" id="bonusResource" value="<?php echo $RESOURCE['resource_tech']; ?>"/></div>
  <div class="span3 control-group" align="right"><div class="input-prepend"><span class="add-on">-</span><input id="companiesTotal" name="companiesTotal" class="input-mini subTotal" type="text" align="right" readonly value="0" /></div></div>
</div><!-- row -->
<div id='companiesDetail' style='display:none'>
<?php
// Payments to Minerals companies
$queryC = "
Select rc.res_name
       ,rc.res_type
       ,rc.res_amount
       ,c.cardno
       ,Case When count(b2.terrno)>0 or p1.terrtype=p.terrtype Then 'Trading'
             Else 'Blockaded'
             End As status
       ,Case When c.running='Y' Then 'Running' Else 'Closed' End
       ,p1.terrname
From sp_board b
Inner Join sp_cards c On b.gameno=c.gameno
                         and b.userno=c.userno
Inner Join sp_res_cards rc On c.cardno=rc.cardno
                              and rc.terrno=b.terrno
Left Join sp_resource r On r.gameno=b.gameno
                           and r.userno=b.userno
Left Join sp_powers p On p.powername=r.powername
Left Join sp_places p1 On p1.terrno=b.terrno
Left Join sp_border bd On b.terrno=bd.terrno_from
Left Join sp_places p2 On p2.terrno=bd.terrno_to
Left Join sp_board b2 On p2.terrno=b2.terrno
                         and b.gameno=b2.gameno
                         and (b2.userno in (0,b.userno) or b.userno=b2.passuser or (char_length(p2.terrtype)=3 and b2.minor=0))
Where char_length(p2.terrtype)!=char_length(p1.terrtype)
 and c.gameno=$gameno
 and c.userno=$userno
Group By b.gameno
       ,b.userno
       ,r.powername
       ,b.terrno
       ,p1.terrname
       ,p.terrtype
       ,p1.terrtype
       ,c.cardno
       ,c.running
       ,rc.res_name
       ,rc.res_type
       ,rc.res_amount
Order by b.gameno
       ,Case When rc.res_type='Minerals' Then 1
             When rc.res_type='Oil' Then 2
             Else 3 End
       ,rc.res_amount desc
       ,rc.res_name
       ,b.terrno
;";
$result = $mysqli -> query("$queryC");
$last_res_type='';

while ($row = $result -> fetch_row()) {
  $res_name = $row[0];
  $res_type = $row[1];
  $res_amount = $row[2];
  $cardno = $row[3];
  $trading = $row[4];
  $running = $row[5];
  $terrname = $row[6];
  $ccost = $orderxml -> xpath("/PAYSALARIES/PayCompany/Cost[../Cardno/text()='".$cardno."']");
  $cvalue = $orderxml -> xpath("/PAYSALARIES/PayCompany/Outstanding[../Cardno/text()='".$cardno."']");
  // Change running for already changed orders
  if ("$ccost[0]" == "$cvalue[0]" and $running=="Closed") $running="Re-open";
  else if ("$ccost[0]" == "0" and $running=="Running") $running="Close";

  if ($last_res_type != $res_type) {?>
    <div class="row-fluid">
      <div class="span8"><h4><?php echo $row[1]; ?></h4></div>
    </div><!-- Resource header row --><?php
    $last_res_type = $res_type;
  }?>

  <div class="row-fluid companyRow">
    <div class="span3"><?php echo $terrname ?><br/><?php echo $res_name; ?></div>
    <div class="span2"><?php if ($trading == 'Blockaded') {?><input type="button" class="btn btn-danger btn-small" value="Blockaded" /><?php } ?></div>
    <div class="span2 resourceValue resource<?php echo $row[1]; if ($trading == 'Blockaded') echo " resourceBlockaded"; ?>" align="center">0/<?php echo $res_amount; ?></div>
    <div class="span2 control-group" align="center"><input type="button" value="<?php echo $running; ?>" class="btn companyButton btn-small" style="width:80px"/></div>
    <div class="span3 control-group" align="right">
      <input id="c<?php echo $cardno; ?>Cost" type="hidden" readonly value="<?php echo $cvalue[0][0]; ?>" />
      <input id="c<?php echo $cardno; ?>Value" name="C<?php echo $cardno; ?>Value" class="input-mini companySum" type="text" align="right" readonly value="0" />
    </div>
  </div><!-- company row --><?php
} ?>
</div><!-- companies detail -->

<div class="row-fluid" style="padding-top:20px">
  <div class="span9"><h3>Final Cash</h3></div>
  <div class="span3 control-group" align="right"><input name="grandTotal" id="grandTotal" type="text" align="right" class="input-mini" readonly value="0"/></div>
</div><!-- row -->
<div class="row-fluid" style="padding-top:20px">
  <div class="span2"><h3>Resources</h3></div>
  <div class="span2" align="center">Initial</div>
  <div class="span2" align="center">Produced</div>
  <div class="span2" align="center">Bonus</div>
  <div class="span2" align="center">Storage</div>
  <div class="span2" align="center">Final</div>
</div><!-- resource header -->
<div class="row-fluid">
  <div class="span2"><h4>Minerals</h4></div>
  <div class="span2" align="center"><input type="text" align="right" class="input-mini" id="mineralsStart" readonly value="<?php echo $RESOURCE['minerals']; ?>" /></div>
  <div class="span2 control-group" align="center"><input type="text" align="right" class="input-mini" id="mineralsTotal" readonly value="0" /></div>
  <div class="span2" align="center"><input type="text" align="right" class="input-mini" id="mineralsBonus" readonly value="0" /></div>
  <div class="span2" align="center"><input type="text" align="right" class="input-mini" id="mineralsMax" readonly value="<?php echo $RESOURCE['max_minerals']; ?>" /></div>
  <div class="span2 control-group" align="right"><input type="text" align="right" class="input-mini" id="mineralsFinal" readonly value="0" /></div>
</div><!-- row -->
<div class="row-fluid">
  <div class="span2"><h4>Oil</h4></div>
  <div class="span2" align="center"><input type="text" align="right" class="input-mini" id="oilStart" readonly value="<?php echo $RESOURCE['oil']; ?>" /></div>
  <div class="span2 control-group" align="center"><input type="text" align="right" class="input-mini" id="oilTotal" readonly value="0" /></div>
  <div class="span2" align="center"><input type="text" align="right" class="input-mini" id="oilBonus" readonly value="0" /></div>
  <div class="span2" align="center"><input type="text" align="right" class="input-mini" id="oilMax" readonly value="<?php echo $RESOURCE['max_oil']; ?>" /></div>
  <div class="span2 control-group" align="right"><input type="text" align="right" class="input-mini" id="oilFinal" readonly value="0" /></div>
</div><!-- row -->
<div class="row-fluid">
  <div class="span2"><h4>Grain</h4></div>
  <div class="span2" align="center"><input type="text" align="right" class="input-mini" id="grainStart" readonly value="<?php echo $RESOURCE['grain']; ?>" /></div>
  <div class="span2 control-group" align="center"><input type="text" align="right" class="input-mini" id="grainTotal" readonly value="0" /></div>
  <div class="span2" align="center"><input type="text" align="right" class="input-mini" id="grainBonus" readonly value="0" /></div>
  <div class="span2" align="center"><input type="text" align="right" class="input-mini" id="grainMax" readonly value="<?php echo $RESOURCE['max_grain']; ?>" /></div>
  <div class="span2 control-group" align="right"><input type="text" align="right" class="input-mini" id="grainFinal" readonly value="0" /></div>
</div><!-- row -->

<?php require("orders_phase1_boomer.php"); ?>
<?php require("orders_phase2.php"); ?>

<!-- Process orders button -->
<div class="row-fluid" style="padding-top:20px">
    <div class="span12" align="center">
        <input type="submit" id="processOrders" value="Process Orders" name="PROCESS" class="btn btn-success"/>
    </div>
</div>
</form>