<?php

// Process orders from phase 1 screen
// $Id: process_phase1.php 237 2014-07-10 07:28:53Z paul $

//? Assume no bad submits

// All info should be in the SR_ORDERXML order, generated by SR_MOVE_QUEUE_INCM
$result = $mysqli -> query ("select order_code From sp_orders Where gameno=$gameno and userno=$userno and ordername='SR_ORDERXML'");
$row = $result -> fetch_row();
$result -> close();

libxml_use_internal_errors(true);
$orderxml = SimpleXML_Load_String($row[0]);

// Update ORDERXML
foreach ($_POST as $key=>$val) {
    if (substr($key,0,1) == 'M') {
        // Minor force
        $order = $orderxml -> xpath("/PAYSALARIES/PayTroops[Terrno/text()='".substr($key,1)."']");
        $order[0] -> Minor = $val;
        $order[0] -> Cost = ($order[0] -> Minor + $order[0] -> Major) * 10;
    } else if (substr($key,0,1) == 'T') {
        // Tanks
        $order = $orderxml -> xpath("/PAYSALARIES/PayTroops[Terrno/text()='".substr($key,1)."']");
        $order[0] -> Major = $val;
        $order[0] -> Cost = ($order[0] -> Minor + $order[0] -> Major) * 10;
    } else if (substr($key,0,3) == 'BNK') {
        // Boomers nukes
        $order = $orderxml -> xpath("/PAYSALARIES/Boomer[Number/text()='".substr($key,3)."']");
        $order[0] -> Nukes = $val;
    } else if (substr($key,0,3) == 'BNE') {
        // Boomers neutron
        $order = $orderxml -> xpath("/PAYSALARIES/Boomer[Number/text()='".substr($key,3)."']");
        $order[0] -> Neutron = $val;
    } else if (substr($key,0,3) == 'BTn') {
        // Boomers terrno
        $order = $orderxml -> xpath("/PAYSALARIES/Boomer[Number/text()='".substr($key,3)."']");
        $order[0] -> Terrno = $val;
    } else if (substr($key,0,2) == 'BT') {
        // Boomers territory
        $order = $orderxml -> xpath("/PAYSALARIES/Boomer[Number/text()='".substr($key,2)."']");
        $order[0] -> Terrname = $val;
    } else if (substr($key,0,2) == 'BV') {
        // Boomers visible
        $order = $orderxml -> xpath("/PAYSALARIES/Boomer[Number/text()='".substr($key,2)."']");
        $order[0] -> Visible = $val;
    } else if (substr($key,0,1) == 'C') {
        // Companies
        $order = $orderxml -> xpath("/PAYSALARIES/PayCompany[Cardno/text()='".substr($key,1,strpos($key,'V')-1)."']");
        $order[0] -> Running = ($val=='0')?'N':'Y';
        if ($order[0] -> Running=='Y') {$order[0] -> Cost = $order[0] -> Outstanding;}
        else {$order[0] -> Cost = '0';}
    } else if ($key == 'Repay') {
        // Repay loan
        $orderxml -> PayBank -> Repay[0] = $val;
    } else if ($key == 'cashValue') {
        // Repay loan
        $orderxml -> Balance -> Credit[0] = $val;
    } else if ($key == 'tbond') {
        // Repay loan
        $orderxml -> PayBank -> Bond[0] = $val;
    } else if ($key == 'Interest') {
        // Repay loan
        $orderxml -> PayBank -> Cost[0] = $val;
    } else if (substr($key,0,2)=="P_" and substr($key,3)=='_val') {
        // Phase 2 costs
        $phase = substr($key,0,3);
        $orderxml -> $phase -> Cost[0] = $val;
    } else if (substr($key,0,2)=="P_" and substr($key,4)=='') {
        // Phase 2 choices
        $orderxml -> $key -> Phase[0] = $val;
    }
}

// Put XML back into the table
$row[0] = $orderxml -> asXML();
$mysqli -> query("update sp_orders set order_code='${row[0]}' where gameno=$gameno and userno=$userno and ordername='SR_ORDERXML'");

// Set orders to submitted
$mysqli -> query("Update sp_orders Set order_code='Orders received' Where gameno=$gameno and userno=$userno and ordername='ORDSTAT'");

// Send message back to the user
$processMessage = "Orders received";

?>
