<?php

// Process orders from phase 5
// $Id: process_phase5.php 199 2014-02-28 20:24:04Z paul $

//? Assume no bad submits

// All info should be in the SR_ORDERXML order, generated by SR_MOVE_QUEUE_BUILD
$result = $mysqli -> query ("select order_code From sp_orders Where gameno=$gameno and userno=$userno and ordername='SR_ORDERXML'") or die($mysqli -> error);
$row = $result -> fetch_row();
$result -> close();

libxml_use_internal_errors(true);
$orderxml = SimpleXML_Load_String($row[0]);

// Update ORDERXML
foreach ($_POST as $key=>$val) {
    if (substr($key,0,2) == 'M-') {
        // Minor force
        $order = $orderxml -> xpath("/BUILD/BuildTroops[Terrno/text()='".substr($key,2)."']");
        $order[0] -> Minor = $val;
    } else if (substr($key,0,2) == 'T-') {
        // Tanks
        $order = $orderxml -> xpath("/BUILD/BuildTroops[Terrno/text()='".substr($key,2)."']");
        $order[0] -> Major = $val;
    } else if (substr($key,0,2) == 'B-') {
        // Boomer
        $order = $orderxml -> xpath("/BUILD/BuildTroops[Terrno/text()='".substr($key,2)."']");
        $order[0] -> Major = $val;
    } else if (substr($key,0,2) == 'S-') {
        $key = Substr($key,2);
        $orderxml -> Strategic -> $key = $val;
    } else if (substr($key,0,4) == 'max_') {
        $orderxml -> Storage -> $key = $val;
    } else if (substr($key,0,3) == 'RA_') {
        $key = Substr($key,3);
        $orderxml -> Research -> $key -> Amt = $val;
    } else if (substr($key,0,3) == 'RV_') {
        $key = Substr($key,3);
        $orderxml -> Research -> $key -> Val = $val;
    }
}

// Put XML back into the table
$row[0] = $orderxml -> asXML();
$mysqli -> query("Update sp_orders set order_code='${row[0]}' where gameno=$gameno and userno=$userno and ordername='SR_ORDERXML'") or die($mysqli -> error);

// Set orders to submitted
$mysqli -> query("Update sp_orders Set order_code='Orders received' Where gameno=$gameno and turnno=$turnno and phaseno=$phaseno and userno=$userno and ordername='ORDSTAT'") or die($mysqli -> error);

// Send message back to the user
$processMessage = "Orders received";

?>